# Generated by Django 6.0.5 on 2026-05-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartidor',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
