# Generated by Django 6.0.5 on 2026-05-18 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_perfilcliente_perfiltrabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.AlterModelOptions(
            name='perfiltrabajador',
            options={'verbose_name': 'Perfil de Trabajador', 'verbose_name_plural': 'Perfiles de Trabajadores'},
        ),
        migrations.AlterModelOptions(
            name='repartidor',
            options={'verbose_name': 'Repartidor', 'verbose_name_plural': 'Repartidores'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.DeleteModel(
            name='PerfilCliente',
        ),
    ]
