# Generated by Django 6.0.5 on 2026-05-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cliente_alter_perfiltrabajador_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='usuario',
            new_name='cliente',
        ),
    ]
